router_settings:
  redis_host: 10.129.247.219
  redis_password: ""
  redis_port: 6379

litellm_settings: 
  callbacks: ["langfuse"]
  redact_user_api_key_info: true
  json_logs: true # Get debug logs in json format
