router_settings:
  redis_host: 10.129.247.219
  redis_password: ""
  redis_port: 6379

litellm_settings:
  set_verbose: False # Switch off Debug Logging, ensure your logs do not have any debugging on
  json_logs: true # Get debug logs in json format
